#!/bin/bash

function check_word() {

	word=$1

	if [ $(echo $word | aspell list) ]; then
		echo \'$word\' mispelled
	fi
}

aspell=$(which aspell)
rv=$?
if [ $rv -gt 0 ]; then
	echo "spellcheck not found"
	exit $rv
fi

# process input method
if [ -t 0 ]; then
	for word; do
		check_word $word
	done
else 
	while read word; do
		check_word $word
	done
fi
