#!/bin/bash

function check_word() {

	word=$1

	if [ $(echo $word | aspell list) ]; then
		echo \'$word\' mispelled
	fi
}

if [ -t 0 ]; then
	for word; do
		check_word $word
	done
else 
	while read word; do
		check_word $word
	done
fi
