#!/usr/bin/python
# interface to the Merriam-Webster thesaurus

import json
import requests
import getopt
import sys
import os

"""
print out a help message
"""
def help():
	print("help")

"""
go get the serialized data. it checks on disk and on the remote server, in the
order specified in the config.
"""
def fetch_resource(filename,url,config):
	resource = None

	for method in config["methods"]:
		if (method == "net") and (resource == None):

			response = requests.get(url)

			if response.status_code == 200:

				resource = response.json()

		if (method == "disk") and (resource == None):
			try:

				with open(filename) as f:
					resource = json.loads(f.read())

			except IOError:
				print("File not accessible")

	return resource


"""
accepts a filename and returns a deserialized representation of the json.
"""
def parse_config(filename):
	config = None
	try:
		with open(filename) as config_file:
			config = json.loads(config_file.read())
	except IOError:
		print("config file not found")

	return config

"""
prepare the request for an entry
"""
def get_body(word,config):
	url = "https://www.dictionaryapi.com/api/v3/references/thesaurus/json/" + word + "?key=" + config["tkey"]
	filename = config["cache_dir"] + "/" + word + ".json"

	json = fetch_resource(filename,url,config)

	return json

"""
"""
def print_data(data,config):
	print("print the data")

"""
parse the command line options and do the work
"""
def main():

	# defaults
	methods = ["net","disk"]
	config_file = os.environ['HOME'] + "/.mwrc"

	# parse command line options
	(args, _) = getopt.getopt(sys.argv[1:], 'hxc:w:')
	for o,a in args:
		if o == "-h":
			help()
			sys.exit()
		elif o == "-w":
			word = a
		elif o == "-x":
			methods = ["disk","net"]
		elif o == "-c":
			config_file = a
		else:
			assert False, "unhandled option"
	
	config = parse_config(config_file)
	config["methods"] = methods

	data = get_body(word, config)

	if not data:
		print("Empty response")
		sys.exit()

	# we received unexpected data
	if 'hwi' not in data[0]:
		print(data)
		sys.exit()

	for i in range(len(data)):
		print("==%d==" %(i+1))
		#print('')
		print("function: "+data[i]["fl"])

		# synonyms
		print("synonyms:")
		for j in range(len(data[i]["meta"]["syns"])):
			print(j+1,end=") ")
			print(', '.join(data[i]["meta"]["syns"][j]))
			#print('')

		# antonyms

		#print_data(word_data,config)

"""
entry point
"""
if __name__ == "__main__":
 	main()
